language: objective-c
xcode_project: Imgix.xcodeproj
xcode_scheme: Imgix
xcode_sdk: iphonesimulator
before_install: rvm use $RVM_RUBY_VERSION
install: bundle install --without=documentation --path ../travis_bundle_dir
after_success: slather
